bug-fix.

diff --git a/.github/workflows/branch-naming-policy.yml b/.github/workflows/branch-naming-policy.yml
--- a/.github/workflows/branch-naming-policy.yml
+++ b/.github/workflows/branch-naming-policy.yml
@@ -26,15 +26,17 @@ jobs:
       - name: Branch Name Pattern Policy
         run: |
             if [[ $branch_name =~ ^feature/.*$ ]]; then
-             
+            echo "Feature Branch Detected."
             elif [[ $branch_name =~ ^release/.*$ ]]; then
+                echo "Release Branch Detected."
                 if [[ ! $branch_name =~ ^release/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-                echo "Error: The semantic version rule must be followed. For example v 1.2.3"
-              
+                echo "Error: The semantic version rule must be followed. For example v1.2.3"
+                exit 1
                 fi
             elif [[ $branch_name =~ ^main ]]; then
-               
+                echo "Main Branch Detected"
             else    
-            echo "Error: Only Feature and Release branches can be created."
-            exit 1
+                echo "Error: Only Feature and Release branches can be created."
+                exit 1
             fi
+      
