type-fix

diff --git a/.github/workflows/branch-naming-policy.yml b/.github/workflows/branch-naming-policy.yml
--- a/.github/workflows/branch-naming-policy.yml
+++ b/.github/workflows/branch-naming-policy.yml
@@ -27,12 +27,12 @@ jobs:
         run: |
             branch_name=${{ github.ref_name }}
             if [[ $branch_name =~ ^feature/.*$ ]]; then
-            echo "Feature Branch Detected."
+                echo "Feature Branch Detected."
             elif [[ $branch_name =~ ^release/.*$ ]]; then
                 echo "Release Branch Detected."
-                if [[ ! $branch_name =~ ^release/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-                echo "Error: The semantic version rule must be followed. For example v1.2.3"
-                exit 1
+                    if [[ ! $branch_name =~ ^release/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+                        echo "Error: The semantic version rule must be followed. For example v1.2.3"
+                    exit 1
                 fi
             elif [[ $branch_name =~ ^main ]]; then
                 echo "Main Branch Detected"
