change strategy

diff --git a/.github/workflows/branch-naming-policy.yml b/.github/workflows/branch-naming-policy.yml
--- a/.github/workflows/branch-naming-policy.yml
+++ b/.github/workflows/branch-naming-policy.yml
@@ -6,7 +6,10 @@ name: Branch Operations
 on:
   # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
-    branches: "**"
+    branches: 
+      - '!main'
+      - '!release/*'
+      - '!feature/*'
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
@@ -28,39 +31,6 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Branch Name Pattern Policy
         id: branch
-        run: |
-            branch_name=${{ github.ref_name }}
-            if [[ $branch_name =~ ^feature/.*$ ]]; then
-                echo "Feature Branch Detected."
-                echo "branchType=feature" >> "$GITHUB_OUTPUT"
-                echo "branchVersion=-" >> "$GITHUB_OUTPUT"
-                exit 0
-            elif [[ $branch_name =~ ^release/.*$ ]]; then
-                echo "Release Branch Detected."
-                    if [[ ! $branch_name =~ ^release/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-                        echo "Error: The semantic version rule must be followed. For example v1.2.3"
-                        exit 1
-                    fi
-                echo "branchType=release" >> "$GITHUB_OUTPUT"
-                semantic_version=$(echo "$branch_name" | sed -n 's/.*\/v\([0-9]*\.[0-9]*\.[0-9]*\)/\1/p')
-                echo "branchVersion=$semantic_version" >> "$GITHUB_OUTPUT"
-                exit 0
-                fi
-            elif [[ $branch_name =~ ^main ]]; then
-                echo "Main Branch Detected"
-                echo "branchType=main" >> "$GITHUB_OUTPUT"
-                echo "branchVersion=-" >> "$GITHUB_OUTPUT"
-                exit 0 
-            else    
-                echo "Error: Only Feature and Release branches can be created."
-                exit 1
-            fi
-  
-  debug:
-    runs-on: ubuntu-latest
-    needs: checkBranch
-    steps:
-      - env:
-          OUTPUT1: ${{needs.checkBranch.outputs.branchType}}
-          OUTPUT2: ${{needs.checkBranch.outputs.branchVersion}}
-        run: echo "$OUTPUT1 $OUTPUT2"
+        run: |   
+              echo "Error: Only Feature and Release branches can be created."
+              exit 1
