error message test

diff --git a/.github/workflows/branch-naming-policy.yml b/.github/workflows/branch-naming-policy.yml
--- a/.github/workflows/branch-naming-policy.yml
+++ b/.github/workflows/branch-naming-policy.yml
@@ -33,5 +33,5 @@ jobs:
       - name: Branch Name Pattern Policy
         id: branch
         run: |   
-              echo "Error: Only Feature and Release branches can be created."
-              exit 1
+            echo "::Error: Only Feature and Release branches can be created."
+            exit 1
